### ISSUE TITLE
Followed directions, get a file copy error related to a missing file

### ISSUE THREAD

**Issue by ethereal-engineer** [rivera-ernesto/AcknowledgementsBundle#1]
```
Pods-acknowledgements.plist -> ../Pods-acknowledgements.plist
```

The destination file doesn't seem to exist. Any thoughts? Thanks.

**Comment by ehlersd** [comment]
If anyone is interested, I added a workaround by using a post_install hook in my Podfile:

'''
post_install do |installer|
    system("rm -f Pods/AcknowledgementsBundle/Pods-default-acknowledgements.plist")
    system("ln -s \"../Target Support Files/Pods-default/Pods-default-acknowledgements.plist\" Pods/AcknowledgementsBundle/Pods-default-acknowledgements.plist")
end
'''

Just replace "default" with your target name...
